server:
  port: 9293

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/programs?ssl=false
    username: user
    password: password
  jpa:
    properties:
      hibernate:
        generate_statistics: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy

  kafka:
    enabled: false
    bootstrap-servers: xx, yy
    properties:
      security.protocol: SSL
    producer:
      bootstrap-servers: xx, yy
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: yy
    topic:
      name: vv
      replicas: 2
      partitions: 3
    profiles-topic:
      name: ff
      replicas: 2
      partitions: 3


multimedia:
  url: http://multimedia
  path: /api/v1/multimedia
  bulk-url: /api/v1/multimedia/bulk


management:
  endpoints:
    web:
      exposure:
        include: '*'

springdoc.api-docs.path: /api/v1/programs/api-doc

logging:
  level:
    com.lehit: DEBUG
    org.springframework.cache: TRACE

health:
  config:
    enabled: false

